Fix revert testcafe version
```
Error: TypeScript compilation failed.
/home/runner/work/ts-angular/ts-angular/tests/top/index.test.ts (12, 11): Property 'expect' does not exist on type 'DoneCallback'.
```