Feature/testcafe (#9)
* Add testcafe

* Fix add e2e to CI

* Fix revert TypeScript version

* Fix downgrade to 3.5.3

* Fix revert testcafe version

```
Error: TypeScript compilation failed.
/home/runner/work/ts-angular/ts-angular/tests/top/index.test.ts (12, 11): Property 'expect' does not exist on type 'DoneCallback'.
```

* Fix use headless at http-server mode